### PR TITLE
Set up permissions for local development

### LINKED ISSUE #468: Failing to load permissions for repo
Command `cargo run ...` building, but fails on running:
```
2025-11-23T22:05:41.099116Z ERROR bors: Error: Failed to load repository bncer/boring-test: Cannot load repository Some("bncer/boring-test"): Could not load permissions for r
epository bncer/boring-test

Caused by:
    Cannot load review users: Cannot load users from team API: reqwest::Error { kind: Status(404, None), url: "https://team-api.infra.rust-lang.org/v1/permissions/bors.boring_test.review.json" }
```
`boring_test` - it's my github repo to test bors

It's because [permissions/bors.rust.review.json](https://team-api.infra.rust-lang.org/v1/permissions/bors.rust.review.json) does not exist for dev environment and json doesn't contain other contributors github UserId.

@Kobzol Can I work on that? 
What method do you suggest to handle local development?

### PR DESCRIPTION
**Pull request by bncer**
Closes #468

I put `Rust Team API url` in README.md not to disclose real api

### CODE REVIEW

File: src/bin/bors.rs [hunk 1]
```diff
@@ -72,6 +72,14 @@ struct Opts {
...
     #[arg(long, env = "WEB_URL", default_value = "http://localhost:8080")]
     web_url: String,
+
+    /// Source of list of users with permissions to perform try/review.
+    #[arg(
+        long,
+        env = "PERMISSIONS",
+        default_value = "https://team-api.infra.rust-lang.org"
+    )]
+    permissions: Option<String>,
```
Comment (Kobzol) [inline src/bin/bors.rs]: This can be just `String`, if you provide the `default_value` attribute, right?

File: README.md [hunk 2]
```diff
@@ -23,6 +23,8 @@ required.
 | `--client-secret`  | `OAUTH_CLIENT_SECRET`|             | GitHub OAuth client secret for rollup UI (optional).      |
 | `--db`             | `DATABASE_URL`       |             | Database connection string. Only PostgreSQL is supported. |
 | `--cmd-prefix`     | `CMD_PREFIX`         | @bors       | Prefix used to invoke bors commands in PR comments.       |
+| `--web_url`        | `WEB_URL`            | http://localhost:8080| Web URL where the bot's website is deployed (optional).|
+| `--permissions`    | `PERMISSIONS`        | Rust Team API url| List of users with permissions to perform try/review (optional).|
```
Comment (Kobzol) [inline README.md]:
```suggestion
| `--permissions`    | `PERMISSIONS`        | Rust Team API url| Either a URL to the team v1 API or a path to a directory containing JSON files with try/review permissions (optional).|
```

File: src/bin/bors.rs (hunk 1 above)
Comment (bncer) [reply src/bin/bors.rs]: Yeah. Thank you

**Comment by bncer** [comment]
No worries. I'm slowly discovering bors with other projects :smile:

File: src/bin/bors.rs [hunk 3]
```diff
@@ -117,7 +125,8 @@ fn try_main(opts: Opts) -> anyhow::Result<()> {
     let db = runtime
         .block_on(initialize_db(&opts.db))
         .context("Cannot initialize database")?;
-    let team_api = TeamApiClient::default();
+    // Unwrap will not panic due to default_value for the 'permissions' argument
```
Comment (Kobzol) [inline src/bin/bors.rs]:
```suggestion

```

**Comment by bncer** [comment]
Thank you! Soon I will open a pr about private key and another pr to complete expected time on pending CI.
