### PR TITLE
fix: ignore unrelated comments

### LINKED ISSUE #124: Do not post a comment for unrelated errors
After every comment on a PR, the bot tries to load the PR information from GitHub. However, this can fail, and in that case the bot starts spamming the PR with [error messages](https://github.com/rust-lang/rust/pull/128861#issuecomment-2286217324). The bot should post a comment when it encounters an error during its operation, but not when it just deals with a comment that is completely unrelated to it. We should first find out whether the comment actually contains a bors command, and if not, we should just always ignore it.

I originally included the PR info loading logic unconditionally to reduce code duplication (so that we always load the PR regardless of the event), but it was a bad idea. We are also needlessly spamming GitHub now, even though most comments are unrelated to bors.

### PR DESCRIPTION
**Pull request by Sakib25800**
Fixes #124

### CODE REVIEW

File: src/tests/mocks/repository.rs [hunk 1]
```diff
@@ -58,6 +58,7 @@ pub struct Repo {
     pub cancelled_workflows: Vec<u64>,
     pub workflow_cancel_error: bool,
     pub pull_requests: HashMap<u64, PullRequest>,
+    pub pull_request_error: bool,
```
Comment (Kobzol) [inline src/tests/mocks/repository.rs:61]: Could you please add a comment here to explain what the field does? Thanks!

File: src/bors/handlers/mod.rs [hunk 2]
```diff
@@ -324,4 +329,15 @@ mod tests {
         })
         .await;
     }
+
+    #[tracing_test::traced_test]
```
Comment (Kobzol) [inline src/bors/handlers/mod.rs:333]:
```suggestion

```
This is mostly for local debugging, we don't need to commit it.

File: src/bors/handlers/mod.rs [hunk 3]
```diff
@@ -324,4 +329,15 @@ mod tests {
...
+    #[sqlx::test]
+    async fn pr_fetch_error(pool: sqlx::PgPool) {
```
Comment (Kobzol) [inline src/bors/handlers/mod.rs:335]:
```suggestion
    async fn do_not_load_pr_on_unrelated_comment(pool: sqlx::PgPool) {
```
Something like this would make it easier to understand what's the test designed for.

**Review by Kobzol — COMMENTED** [review]
I checked the code again and it seems like we didn't spam the repo with error comments anymore :sweat_smile: We would produce an error in the log though, and mainly we would spam GitHub, both of which is not needed, so this PR is still a nice improvement.

Thank you! Left a few nits.

**Comment by Kobzol** [comment]
Thanks! Please squash the changes and we're good to go. Looks like I'll also need to fix CI.

**Comment by Sakib25800** [comment]
This is part of what using bors would have solved right? 😆

**Review by Kobzol — APPROVED** [review]
